import org.apache.tools.ant.taskdefs.condition.Os
import org.apache.tools.ant.filters.ReplaceTokens

apply plugin: 'war'
apply plugin: 'distribution'

defaultTasks 'build'

repositories {
    mavenCentral {
        content {
            excludeModule('javax.media', 'jai_core')
        }
    }
    maven { url = 'https://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts' }
    maven { url = 'https://repo.osgeo.org/repository/release/' }
}

// the task `run` of the gretty plugin conflicts with the task with the same
// name of the plugin `application`. that's why the following tasks are defined
// manually.
tasks.register('startScripts', CreateStartScripts) {
}
tasks.register('print', JavaExec) {
    mainClass = 'org.mapfish.print.cli.Main'
    classpath = sourceSets.main.runtimeClasspath
}

// define what should be included as distribution.
distributions {
    main {
        contents {
            from 'src/dist'

            into('lib') {
                from(jar)
                from(project.configurations.runtimeClasspath)
            }
            into('bin') {
                from(startScripts)
                filePermissions { unix(0755) }
            }
        }
    }
}


def appDir = new File(getLayout().getBuildDirectory().getAsFile().get(), 'install')
installDist.doFirst {
    appDir.deleteDir()
}
tasks.withType(Javadoc).configureEach {
    options.encoding = 'utf-8'
    title = "Mapfish Print Core Module $version"
    if (JavaVersion.current().isJava9Compatible()) {
        options.addBooleanOption('html5', true)
    }
}
tasks.register('testCLI', Exec) {
    dependsOn installDist
    workingDir new File(appDir, 'core/bin')
    def cmd
    if (Os.isFamily(Os.FAMILY_WINDOWS)) {
        cmd = ['cmd', '/c', 'print.bat']
    } else {
        cmd = ['./print']
    }

    File outputFile = new File(appDir, 'cliTestOutput.png')
    File configFile = file('src/test/resources/org/mapfish/print/cli/config.yaml')
    File v3ApiRequestFile = file('src/test/resources/org/mapfish/print/cli/v3Request.json')
    cmd.addAll([
        '-config', configFile.getAbsolutePath(),
        '-spec', v3ApiRequestFile.getAbsolutePath(),
        '-output', outputFile.getAbsolutePath()])
    commandLine cmd
    environment('JAVA_OPTS', '-Xmx500m')
    doFirst {
        println("Testing CLI application: $workingDir")
        outputFile.delete()
        assert !outputFile.exists()
    }
    doLast {
        assert outputFile.exists()
        assert outputFile.length() > 0
    }
}

test {
    reports {
        junitXml.getRequired().set(true)
        html.getRequired().set(true)
    }
    maxHeapSize = "2G"
    useJUnitPlatform()
}

build {
    dependsOn(tasks.distZip)
    dependsOn(tasks.testCLI)
    processTestResources.mustRunAfter(javadoc)
}

configurations {
    compile.transitive = true

    metrics {
        description = 'Libraries for measuring performance and load. See https://github.com/dropwizard/metrics'
    }
    implementation.extendsFrom(metrics)
    geotools {
        description = 'Geotools spatial libraries'
    }
    implementation.extendsFrom(geotools)
    jasper {
        description = 'Dependencies for the jasper reports generation'
    }
    implementation.extendsFrom(jasper)

    // Want to use the slf4j bridge instead
    all*.exclude group: 'commons-logging'
    // Obscure stack trace if we let this dependency: https://stackoverflow.com/a/15808940
    all*.exclude module: 'xercesImpl'
}



dependencies {
    implementation(
        libs.spring.context,
        libs.spring.core,
        libs.spring.web,
        libs.spring.webmvc,
        libs.spring.aspects,
        libs.spring.orm,
        libs.spring.jdbc,
        libs.spring.tx,
        libs.spring.test,
        libs.spring.security.config,
        libs.spring.security.web,
        libs.cors.filter,
        libs.hibernate.core,
        libs.postgresql,
        libs.hypersistence.utils.hibernate63,
        libs.c3p0,
        libs.jai.core,
        libs.jakarta.annotation.api,
        libs.jakarta.persistence.api,
        libs.jakarta.servlet.api,
        libs.checker.qual,
        libs.icu4j,
    )
    metrics(
        libs.metrics.core,
        libs.metrics.jakarta.servlet,
        libs.metrics.jakarta.servlets,
        libs.metrics.httpclient,
        libs.metrics.jvm,
        libs.metrics.jmx,
        libs.metrics.logback,
    )
    geotools(
        libs.geotools.gt.epsg.hsql,
        libs.geotools.gt.render,
        libs.geotools.gt.geojson,
        libs.geotools.gt.geotiff,
        libs.geotools.gt.wms,
        libs.geotools.gt.xsd.gml3,
        libs.geotools.gt.svg,
        libs.geotools.gt.cql,
    )
    implementation libs.httpclient5
    jasper(
        libs.dynamicjasper,
        libs.itextpdf,
        libs.jasperreports,
        libs.jasperreports.excel.poi,
        libs.jasperreports.fonts,
        libs.jasperreports.functions,
        libs.jasperreports.json,
        libs.jasperreports.jdt,
        libs.jasperreports.pdf,
    )
    implementation(
        libs.slf4j.api,
        libs.slf4j.jcl.over.slf4j,
        libs.slf4j.jul.to.slf4j,
        libs.logback.classic,
        libs.json,
        libs.snakeyaml,
        libs.cli.parser,
        libs.javax.mail,
        libs.aws.java.sdk.s3,
        libs.sentry.logback,
        // For JSON logs
        libs.logstash.logback.encoder,
        // For PDF/A
        libs.adobe.xmpcore,
        // For JasperReports
        libs.joda.time,
        libs.jcommon,
        libs.groovy.all,
        libs.xalan.serializer,
        // For WebP images
        libs.imageio.webp,
    )

    implementation(
        libs.batik.codec,
        libs.batik.svg.dom,
    )

    compileOnly libs.spotbugs.annotations

    testImplementation(
        libs.javamail.mock2.fullmock,
        libs.h2,
        libs.junit.jupiter,
        libs.junit.jupiter.api,
    )
}

static def gitRevision() {
    def gitRev = System.getenv('GIT_HEAD')
    return gitRev != null ? gitRev : 'git rev-parse HEAD'.execute().text.trim()
}

compileTestJava {
    options.deprecation = true
    options.compilerArgs = ['-Xlint:unchecked']
}

// Add version to resources, used for User-Agent string:
processResources {
    filter ReplaceTokens, tokens: [
        'application.version': version
    ]
}

def addManifestAttribute(manifest) {
    manifest.mainAttributes(
        'Mapfish-Print-Version': version,
        'Git-Revision': gitRevision(),
        'Build-Time': new Date().getDateTimeString(),
        'Build-By': System.getProperty('user.name', 'unknown'),
        'Build-Java-Runtime-Name': System.getProperty('java.runtime.name', 'unknown'),
        'Build-Java-Version': System.getProperty('java.version', 'unknown'),
        'Build-OS-Arch': System.getProperty('os.arch', 'unknown'),
        'Build-OS-Name': System.getProperty('os.name', 'unknown')
    )
}

jar {
    enabled = true
    archiveBaseName = 'print-lib'
    addManifestAttribute(manifest)
}

war {
    archiveBaseName = 'print-servlet'
    addManifestAttribute(manifest)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    webAppDirectory = file('src/main/webapp')
}

tasks.register('show') {
}

show.doLast {
    war.classpath.files.each { println it }
}

tasks.register('libJavadocJar', Jar) {
    dependsOn javadoc
    archiveBaseName = 'print-lib'
    archiveClassifier = 'javadoc'
    from 'build/docs/javadoc'
}


tasks.register('libSourcesJar', Jar) {
    archiveBaseName = 'print-lib'
    from sourceSets.main.allSource
    archiveClassifier = 'sources'
}


gradle.taskGraph.whenReady { taskGraph ->
    if (taskGraph.hasTask(print)) {
        if (project.hasProperty('printArgs')) {
            print.args printArgs.toString().split(" ").toList()
        } else {
            throw new IllegalArgumentException('You must supply the -PprintArgs="..." arguments.\nFor Example:\n\n./gradlew print ' +
                '-PprintArgs="-config examples/config.yaml -spec examples/spec.json -output ./output.pdf"\n\n')
        }
    }
}

startScripts {
    // Clear up the classpath because the launcher jar has it.
    applicationName = 'print'
    mainClass = 'org.mapfish.print.cli.Main'
    classpath = files(jar.archiveFile)
    outputDir = layout.buildDirectory.dir('scripts').get().asFile

    doLast {
        fileTree(startScripts.outputDir).each { file ->
            def encoding = 'UTF-8'
            // There was a bug in the start script where all jars were listed and that failed in windows.
            // now I just have the main jar and replace it with * so that all jars in that directory
            // are loaded on classpath.
            file.setText(file.getText(encoding).replace(jar.archiveFile.get().getAsFile().name, '*'), encoding)
        }
    }
}

tasks.register('explodedWar', Sync) {
    into layout.buildDirectory.dir('webapp')
    with war
}

tasks.withType(Test).configureEach { t ->
    addTestListener(new TestListener() {
        @Override
        void beforeSuite(TestDescriptor suite) {}

        @Override
        void beforeTest(TestDescriptor testDescriptor) {}

        @Override
        void afterTest(TestDescriptor testDescriptor, TestResult result) {}

        @Override
        void afterSuite(TestDescriptor desc, TestResult result) {
            if (desc.parent != null) return // only print once, for the outermost suite
            println ""
            println "Core test ${t.path} summary: ${result.resultType} " +
                "(${result.testCount} tests, " +
                "${result.successfulTestCount} passed, " +
                "${result.failedTestCount} failed, " +
                "${result.skippedTestCount} skipped)"
        }
    })
}
