#!/usr/bin/env python3

import requests


def main():
    response = requests.get("http://localhost:8080/print/fonts")

    assert response.ok, response.status_code
    assert response.headers["Content-Type"] == "application/json;charset=utf-8", response.headers[
        "Content-Type"
    ]
    fonts_result = response.json()

    fonts = [
        "DejaVu Sans",
        "DejaVu Serif",
        "DejaVu Sans Mono",
        "JasperReports Icons",
        "Cadastra",
    ]
    for font in fonts:
        assert font in fonts_result["jasperreportFonts"], "{} not in [{}]".format(
            font, ", ".join(fonts_result["jasperreportFonts"])
        )

    fonts = {
        "Font Awesome 5 Free Solid": [
            {
                "families": ["Font Awesome 5 Free", "Font Awesome 5 Free Solid"],
                "name": "Font Awesome 5 Free Solid",
                "styles": ["Solid"],
                "weight": 900,
            }
        ],
        "Font Awesome 5 Free Regular": [
            {
                "families": ["Font Awesome 5 Free", "Font Awesome 5 Free Regular"],
                "name": "Font Awesome 5 Free Regular",
                "styles": ["Regular"],
                "weight": 400,
            }
        ],
        "Font Awesome 5 Brands Regular": [
            {
                "families": ["Font Awesome 5 Brands", "Font Awesome 5 Brands Regular"],
                "name": "Font Awesome 5 Brands Regular",
                "styles": ["Regular"],
                "weight": 400,
            }
        ],
        "Cadastra": [],
    }

    for font, fontconfig in fonts.items():
        font_result = [f for f in fonts_result["fonts"] if f["family"] == font]
        assert len(font_result) == 1
        assert font_result[0]["fontconfig"] == fontconfig, f"Invalid {font}: " + str(
            font_result[0]["fontconfig"]
        )


if __name__ == "__main__":
    main()
