#!/bin/bash -x
container_name=mapfish-print-$RANDOM

function cleanup() {
    docker rm -f $container_name
}

docker run --detach --rm --network none --name $container_name camptocamp/mapfish_print:latest
# let the container initialize
sleep 15

server_status=$(docker logs $container_name 2>&1 | grep 'INFO \[main\] org.apache.catalina.startup.Catalina.start Server startup')
if [[ -z "${server_status}" ]]; then
    echo "container unhealthy"
    docker logs $container_name
    cleanup
    exit 1
else
    echo "1st check ok"
    cleanup
fi

docker run --detach --rm --name $container_name camptocamp/mapfish_print:latest
sleep 15
http_code=$(docker exec $container_name curl -sL -w "%{http_code}" -I localhost:8080/metrics/healthcheck -o /dev/null)
if [[ $http_code = 200 ]]; then
    echo "container healthy"
    cleanup
    exit 0
else
    echo "container unhealthy"
    cleanup
    exit 1
fi
